version: '3'

tasks:
  env:venv:
    desc: "Create venv environment"
    # The status check prevents the task from running if the directory exists
    status:
      - test -d .venv
    cmds:
      - python3 -m venv .venv

  deps:
    desc: "Download dependencies."
    # Ensures the venv is created before trying to install dependencies
    deps: 
      - env:venv
    # Taskfile will only run this if requirements.txt is newer than our marker file
    sources:
      - requirements.txt
    generates:
      - .venv/.deps_installed
    cmds:
      - echo "📦 Downloading dependencies..."
      # Use the pip inside the venv directly
      - .venv/bin/pip install -r requirements.txt
      # Create a hidden marker file so Taskfile knows the install finished successfully
      - touch .venv/.deps_installed

  run:
    desc: "Main application. Run with arg `--help` for more details."
    # Ensures dependencies are installed before trying to run the app
    deps: 
      - deps
    cmds:
      # Use the python inside the venv directly
      - .venv/bin/python -m src.main {{.CLI_ARGS}}